import Head from "next/head";
import Image from "next/image";
import Card from "./../components/ProductDisplay/Card";
import AllProducts from "@/components/Products/AllProducts";
import Sidecard from "@/components/Sidecard/Sidecard";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<Card />
				<AllProducts />
				<Sidecard />
			</div>
		</>
	);
}
